### PR TITLE
Support ruby 210

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by cyberious** [comment]
The matrix here would be too large, and for a longer churn and not much benefit for validation.  I would prefer to hit major milestones for testing matrix, like Puppet  3.4, 3.6 and 3.7.  3.5 is really something most people will not use as we dropped quickly.

**Comment by cmurphy** [comment]
Could we have this look a bit more like https://github.com/puppetlabs/puppetlabs-rabbitmq/blob/master/.travis.yml ? This would be more in line with what the other modules are doing. It uses three different ruby versions, one intermediate puppet 3.x version, latest 3.x, and the future parser.

If that's not a workable model for this I'd like to talk about updating that file for all the modules besides just this one.

**Comment by ghoneycutt** [comment]
@cmurphy suggest using this .travis.yml actually, though with the additional checks for future parser. I'll work on adding those.

https://github.com/ghoneycutt/puppet-module-hosts/blob/master/.travis.yml

I do not agree with @cyberious with regards to testing methodology. Each feature release should be explicitly tested. Worrying about module churn is over optimizing for no benefit since testing is free. The only downside is that it takes a bit longer with more tests, but that is not a constraint as PR's generally take many orders of magnitude more time to complete than any tests. By testing each feature release there is more confidence that it will work for more people and without surprises. It also clearly documents the supported platforms.

**Comment by tphoney** [comment]
@ghoneycutt the travis.yml has changed significantly since then. I dont think this is needed anymore should it be closed ?

**Comment by ghoneycutt** [comment]
@tphoney Travis allows error for Puppet v4 though the metadata states that v4 is supported. Recommend removing the allow_failures bit for Puppet v4.

**Comment by tphoney** [comment]
I have put in #191 I will close this PR. Apologies for the slowness.

**Pull request closed without merging**
