### PR TITLE
Added update_only_on_refresh Parameter to ini_setting

### PR DESCRIPTION
**Pull request by puppetalan**
OK, you're probably thinking "what the h-e-double-hockey-sticks do we need that for??"

Well, I do have a use case. I was working with a customer recently whose ini files (used by some application) contain timestamps indicating when the associated values were changed. For example, the ini file might have something like this:

[main]
xyz = 12
xyz_timestamp = 2016-03-14 15:10:43

And whenever the value for xyz is changed, they need to update the timestamp (but not otherwise). Sure, we could have done some nasty exec or augeas crap, but isn't it so much more elegant to do something like this:

ini_setting { 'xyz':
  ensure  => present,
  path    => '/tmp/file.ini',
  section => 'main',
  setting => 'xyz',
  value   => '12',
  notify  => Ini_Setting['xyz_timestamp'],
}
ini_setting {'xyz_timestamp':
  ensure                 => present,
  path                   => '/tmp/file.ini',
  section                => 'foo',
  setting                => 'xyz_timestamp',
  value                  => strftime('%Y-%m-%d %H:%M:%S'),
  update_only_on_refresh => true,
}

As such, the time only gets updated if the setting changes.

Anyway, this solves the issue for this particular customer, but I thought that maybe it might be of interest to the general population.

### CODE REVIEW

**Comment by igalic** [comment]
@puppetalan two comments:
* i'd much prefer this to be consistent with exec and other resources and be named `refreshonly`.
* your first commit seems… strange.

**Comment by hunner** [comment]
:+1: what igalic said. Otherwise I'm pretty much always in favor of `refreshonly` as a parameter anywhere.

**Comment by puppetalan** [comment]
I would have liked to call it refreshonly but to me that implies that it
_only_ responds to a refresh. I couldn’t figure out (without rewriting the
whole thing) how to avoid always doing a create, hence why i named it the
way I did. Of course, I’m happy to change it.

- alan

On Mon, Mar 14, 2016 at 3:23 PM, Hunter Haugen <notifications@github.com>
wrote:

> [image: :+1:] what igalic said. Otherwise I'm pretty much always in favor
> of refreshonly as a parameter anywhere.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/puppetlabs/puppetlabs-inifile/pull/203#issuecomment-196547117>
> .
>



-- 
Alan Petersen
Professional Services Engineer
Puppet

**Comment by jonnytpuppet** [comment]
@puppetalan It would be great if you could squash the commits and rename the param, just to keep it consistent with the other modules. This is a really neat feature, though! :)

Also, please have a look at why there is a merge in the commit history. That probably shouldn't be there so you may need to copy-paste your code onto a clean branch (at latest master HEAD).

Cheers

JT

**Comment by jonnytpuppet** [comment]
Closing this PR due to #207 

Thanks!

**Pull request closed without merging**
