### PR TITLE
Modernize Travis-ci configurations and enable use of containers

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@mhaskel Do you mind reviewing this? I kept the same levels of support except the call out for different versions of facter with Puppet v2.7.  Though hoping we can drop that too. https://tickets.puppetlabs.com/browse/MODULES-1772

**Comment by igalic** [comment]
i think we should probably push this into [modulesync](https://github.com/puppetlabs/modulesync)
i'd also like to see strict variables and parser=future options…

**Comment by ghoneycutt** [comment]
@igalic is this a good start that could be merged as it explicitly tests the same functionality and then some while doing it much faster?

**Comment by ghoneycutt** [comment]
Closing as @cyberious is reviewing in #151 which contains this commit.

**Pull request closed without merging**
