### PR TITLE
Update modulesync_config [a3fe424]

### PR DESCRIPTION
**Pull request by DavidS**

### CODE REVIEW

**Comment by DavidS** [comment]
Created https://tickets.puppetlabs.com/browse/MODULES-3793 for the CI failure. This can be merged.

**Comment by DavidS** [comment]
A fix for the test failure is in flight in #216

**Comment by DavidS** [comment]
From https://github.com/puppetlabs/modulesync_configs/pull/90

**Comment by tphoney** [comment]
still failing

**Comment by DavidS** [comment]
still waiting for #216 to land.

**Comment by DavidS** [comment]
rebased on `release` to test the changes there. should not be merged yet.

**Comment by DavidS** [comment]
Can be merged once travis is done.

**Pull request merged**
