### PR TITLE
Add insert_type and subsetting_key_val_separator

### PR DESCRIPTION
**Pull request by dmitryilyin**
* Insert_type and imsert value can define where
      a new subsetting element will be placed.
    * subsetting_key_val_separator allows you to have
      a separator character between a subsetting name
      and its value.
    * Refactor ini_subsetting and its spec.

### CODE REVIEW

**Comment by dmitryilyin** [comment]
@DavidS could you please look

**Comment by dmitryilyin** [comment]
hello?

**Comment by DavidS** [comment]
Awesome code! Thank you so much.

**Comment by dmitryilyin** [comment]
Could you, please, make 1.5.1 tag?

**Comment by DavidS** [comment]
I've scheduled a release for our next sprint.

**Pull request merged**
