### PR TITLE
Add support for multiple values per key

### PR DESCRIPTION
**Pull request by omolenkamp**
This change adds support for ini files in which the same key is used multiple times for lists of values, for example:
```
[section]
foo=a
foo=b
```
To set multiple values, an array of values can be passed to the `value` property of `ini_setting`.

When passing a single value, the module works as before, with one exception: when a single value is passed to `value`, but the ini file already contains multiple lines with the same key, any additional lines will now be removed instead of retained.

### CODE REVIEW

**Comment by chelnak** [comment]
Hey @omolenkamp , thank you for your contribution. Looks like we have failures in both spec and acceptance tests for this.

Is it something that you could take a look at? We are here to help if you need anything.

**Comment by omolenkamp** [comment]
All PR Testing jobs are failing on the step "Install agent", but it doesn't look like that's something I broke.

**Comment by chelnak** [comment]
Hey, I think these issues should be resolved now. I'll re kick the tests 🙂

**Comment by LukasAud** [comment]
It looks like there is a single failure occurring across all OSs. Something related to change logging. If this issue is fixed, we should have no problem merging this PR.

**Comment by kenyon** [comment]
Keep open.

**Comment by david22swan** [comment]
Closing and re-opening to re-kick the tests as the logs of the last run have been discarded.

**Comment by LukasAud** [comment]
Hi @omolenkamp, it seems like your PR has been stale for a while. Our team is currently cleaning up our modules and we are looking to address any stale PRs. Since there hasn't been any engagement for a long time, we have decided to put this PR back on our 'attention-needed' list. Please be aware that PRs with this tag are generally closed within 1-2 weeks if there is no response back from the author and/or engagement from the community. Please be aware that closed PRs an be reopened if the author wants to continue working on them!

Since your PR is a potential fix for one of our currently ongoing issues with the module, we can also keep it open if someone else volunteers to 'adopt' this PR and you agree with it.

Thanks for your understanding.

**Comment by omolenkamp** [comment]
Sorry, haven't looked at this issue for a while. If the tests can be run again to produce new logs, I'll try to fix the remaining bug soon.

**Comment by jordanbreen28** [comment]
@omolenkamp - looks like our github bot wrongly closed this PR. I've re-opened to kick the tests off like you requested. Apologies for the delay in noticing this!

**Comment by jordanbreen28** [comment]
Hey @omolenkamp!
I'm going to go ahead and close this PR again due to lack of engagement. If you get some time to address the test failures please do re-open this request and we'll take it from here.

**Comment by vmpr** [comment]
reopen
@omolenkamp can you please finish that MR? we also need it but I am not able to write in myself :(

**Pull request closed without merging**
